### ISSUE TITLE
UnsafeLoaderWarning after Rasa_Core 0.9.5 -> 0.10.0

### ISSUE THREAD

**Issue by MxmRz** [schul-cloud/cui#20]
After updating Rasa_core from 0.9.5 to 0.10.0:
When bringing the project up with "docker-compose up" I get an UnsafeLoaderWarning.
All "yaml.load(stream)" occurences should be replaced with "yaml.safe_load(stream)" now. However I could not find any uses of "yaml.load(stream)".

> Using TensorFlow backend.
rasa-core_1          | 2018-12-01 16:29:45 WARNING  py.warnings  - /usr/local/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning:
rasa-core_1          | The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
rasa-core_1          | Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
rasa-core_1          | Alternatively include the following in your code:
rasa-core_1          |
rasa-core_1          |   import warnings
rasa-core_1          |   warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
rasa-core_1          |
rasa-core_1          | In most other cases you should consider using 'safe_load(stream)'
rasa-core_1          |   data = yaml.load(stream)

**Comment by janrenz** [comment]
I think we can ignore this, this must be changed in the rasa code, or?

**Comment by MxmRz** [comment]
Meaning, that further updating the rasa-core should fix it? 
Or do you mean, that the ignore filter should be used? If so, do you have an idea where it should be implemented?

**Comment by MxmRz** [comment]
I tried adding `import warnings` and `warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)` in the `rasa-core/server.py` directory. 

It is the only directory I could find in which `load()` is used.

It leads to this warning: 

> rasa-core_1          | Traceback (most recent call last):
rasa-core_1          |   File "run_server.py", line 5, in <module>
rasa-core_1          |     from server import create_app
rasa-core_1          |   File "/app/server.py", line 40, in <module>
rasa-core_1          |     warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
rasa-core_1          | NameError: name 'ruamel' is not defined

I even added `ruamel.yaml==0.15.66` to `rasa-core/requirements.txt` and made sure it is installed using `pip install -r requirements.txt` in the right directory, but it still gives the same warning.
