### ISSUE TITLE
BadZipFile after Rasa_Core 0.9.5 -> 0.10.0

### ISSUE THREAD

**Issue by MxmRz** [schul-cloud/cui#21]
After updating Rasa_core from 0.9.5 to 0.10.0:
When bringing the project up with "docker-compose up" I get a BadZipFile Error. 

> | 2018-12-01 16:29:52+0000 [-] "172.18.0.4" - - [01/Dec/2018:16:29:51 +0000] "GET / HTTP/1.1" 200 27 "-" "python-requests/2.18.4"
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-] Exception in thread Thread-1:
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-] Traceback (most recent call last):
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     self.run()
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/threading.py", line 864, in run
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     self._target(*self._args, **self._kwargs)
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/project.py", line 145, in _run_model_pulling_worker
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     _update_model_from_server(model_server, project)
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/project.py", line 76, in _update_model_from_server
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     model_server, model_directory, project.fingerprint)
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu/project.py", line 133, in _pull_model_and_fingerprint
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     zip_ref = zipfile.ZipFile(IOReader(response.content))
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/zipfile.py", line 1108, in __init__
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     self._RealGetContents()
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]   File "/usr/local/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]     raise BadZipFile("File is not a zip file")
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-] zipfile.BadZipFile: File is not a zip file
rasa-nlu_1           | 2018-12-01 16:29:52+0000 [-]

**Comment by janrenz** [comment]
Passiert das bei allen environments?

**Comment by MxmRz** [comment]
Yes, the error appears with all environments: opensap_faq, openwho_faq, openhpi_faq_de, openhpi_faq_eng
